### ISSUE TITLE
Unstable test: AsyncBarrierTests.StressMultipleGroups

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-threading#119]
From [appveyor log](https://ci.appveyor.com/project/AArnott/vs-threading/build/15.3.25+g24bc70716b.R#L89):

```
[xUnit.net 00:00:12.1576651]     Microsoft.VisualStudio.Threading.Tests.AsyncBarrierTests.StressMultipleGroups(players: 2, groupSize: 1) [FAIL]
[xUnit.net 00:00:12.1588364]       System.TimeoutException : The operation has timed out.
[xUnit.net 00:00:12.1603051]       Stack Trace:
[xUnit.net 00:00:12.1662236]         C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading\TplExtensions.cs(82,0): at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__5.MoveNext()
[xUnit.net 00:00:12.1663510]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:12.1667640]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:12.1668505]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:12.1669229]         C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\AsyncBarrierTests.cs(68,0): at Microsoft.VisualStudio.Threading.Tests.AsyncBarrierTests.<StressMultipleGroups>d__5.MoveNext()
[xUnit.net 00:00:12.1670373]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:12.1671195]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:12.1671748]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:12.1672228]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:12.1672743]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:12.1673292]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:12.1673762]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:12.1674371]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:12.1674909]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   Microsoft.VisualStudio.Threading.Tests.AsyncBarrierTests.StressMultipleGroups(players: 2, groupSize: 1)
Error Message:
 System.TimeoutException : The operation has timed out.
Stack Trace:
   at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__5.MoveNext() in C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading\TplExtensions.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.Tests.AsyncBarrierTests.<StressMultipleGroups>d__5.MoveNext() in C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\AsyncBarrierTests.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by AArnott** [comment]
[Still fails](https://ci.appveyor.com/project/AArnott/vs-threading/build/15.6.4+ge1646b17d5.R#L104)

**Comment by AArnott** [comment]
It [still fails](https://ci.appveyor.com/project/AArnott/vs-threading/build/15.3.41+gd5504b53cb.R#L104).

```
Failed   Microsoft.VisualStudio.Threading.Tests.AsyncBarrierTests.StressMultipleGroups(players: 2, groupSize: 1)
Error Message:
 System.TimeoutException : The operation has timed out.
Stack Trace:
   at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__5.MoveNext() in C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading\TplExtensions.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.Tests.AsyncBarrierTests.<StressMultipleGroups>d__5.MoveNext() in C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\AsyncBarrierTests.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

It notably seems to happen only on CoreCLR test runs.
