### ISSUE TITLE
Unstable test: WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#184]
The `WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations` test failed in [this build](https://ci.appveyor.com/project/AArnott/vs-threading/build/15.6.4-beta+gc5ec8495ec#L159) of [this commit](https://github.com/Microsoft/vs-threading/commit/c5ec8495ecab6aa281974bd0e1a981f626abff0c), on netcoreapp1.0 with this output:

```
[xUnit.net 00:00:23.1898614]     Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations [FAIL]
[xUnit.net 00:00:23.1900792]       Assert.True() Failure
[xUnit.net 00:00:23.1901357]       Expected: True
[xUnit.net 00:00:23.1901791]       Actual:   False
[xUnit.net 00:00:23.1911563]       Stack Trace:
[xUnit.net 00:00:23.1949805]         C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs(185,0): at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.<>c__DisplayClass12_0.<WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations>b__0(Task <p0>)
[xUnit.net 00:00:23.1951428]            at System.Threading.Tasks.Task.Execute()
[xUnit.net 00:00:23.1955434]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:23.1956298]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:23.1956947]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:23.1957651]         C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs(201,0): at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations()
Failed   Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations
Error Message:
 Assert.True() Failure
Expected: True
Actual:   False
Stack Trace:
   at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.<>c__DisplayClass12_0.<WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations>b__0(Task <p0>) in C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs:line 185
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations() in C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs:line 201
```

**Comment by AArnott** [comment]
It just [failed again](https://ci.appveyor.com/project/AArnott/vs-threading/build/15.6.60+gc2cfc7ae7f#L260):

```
[xUnit.net 00:00:11.7622860]     Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations [FAIL]
[xUnit.net 00:00:11.7628571]       Assert.True() Failure
[xUnit.net 00:00:11.7631456]       Expected: True
[xUnit.net 00:00:11.7634390]       Actual:   False
[xUnit.net 00:00:11.7651026]       Stack Trace:
[xUnit.net 00:00:11.7727745]         C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs(185,0): at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.<>c__DisplayClass12_0.<WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations>b__0(Task <p0>)
[xUnit.net 00:00:11.7777274]            at System.Threading.Tasks.Task.Execute()
[xUnit.net 00:00:11.7839120]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:11.7842048]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:11.7844149]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:11.7846514]         C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs(201,0): at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations()
Failed   Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations
Error Message:
 Assert.True() Failure
Expected: True
Actual:   False
Stack Trace:
   at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.<>c__DisplayClass12_0.<WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations>b__0(Task <p0>) in C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs:line 185
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations() in C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs:line 201
```

**Comment by AArnott** [comment]
And [again](https://ci.appveyor.com/project/AArnott/vs-threading/build/16.0.42-beta+gb26dd38371#L917):

    WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs(184,0): at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.<>c__DisplayClass12_0.<WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations>b__0(Task <p0>)
           at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
           at System.Threading.Tasks.Task.Execute()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs(198,0): at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations()

**Comment by AArnott** [comment]
And [again](https://andrewarnott.visualstudio.com/OSS/_build/results?buildId=399&view=logs):

```
2018-10-11T16:36:31.6536391Z [xUnit.net 00:00:25.0739443]     Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations [FAIL]
2018-10-11T16:36:31.6540864Z [xUnit.net 00:00:25.0752589]       Assert.True() Failure
2018-10-11T16:36:31.6559506Z [xUnit.net 00:00:25.0753547]       Expected: True
2018-10-11T16:36:31.6559804Z [xUnit.net 00:00:25.0754185]       Actual:   False
2018-10-11T16:36:31.6560002Z [xUnit.net 00:00:25.0766046]       Stack Trace:
2018-10-11T16:36:31.7247973Z [xUnit.net 00:00:25.0830018]            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-10-11T16:36:31.7532267Z [xUnit.net 00:00:25.0831415]            at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2018-10-11T16:36:31.7533627Z [xUnit.net 00:00:25.0832056]         --- End of stack trace from previous location where exception was thrown ---
2018-10-11T16:36:31.7533891Z [xUnit.net 00:00:25.0832976]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-10-11T16:36:31.7534126Z [xUnit.net 00:00:25.0833762]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-11T16:36:31.7534426Z [xUnit.net 00:00:25.0834611]         D:\a\1\s\src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs(201,0): at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations()
2018-10-11T16:36:31.7534636Z Failed   Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations
2018-10-11T16:36:31.7535515Z Error Message:
2018-10-11T16:36:31.7535732Z  Assert.True() Failure
2018-10-11T16:36:31.7535934Z Expected: True
2018-10-11T16:36:31.7536138Z Actual:   False
2018-10-11T16:36:31.7536316Z Stack Trace:
2018-10-11T16:36:31.7536509Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-10-11T16:36:31.7536725Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2018-10-11T16:36:31.7536913Z --- End of stack trace from previous location where exception was thrown ---
2018-10-11T16:36:31.7537125Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-10-11T16:36:31.7537318Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-11T16:36:31.7537523Z    at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations() in D:\a\1\s\src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs:line 201
```

**Comment by AArnott** [comment]
and [again](https://dev.azure.com/azure-public/vside/_build/results?buildId=1284) (on dda65cd):

```
2018-12-21T02:28:46.0772809Z Failed   Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations
2018-12-21T02:28:46.0773135Z Error Message:
2018-12-21T02:28:46.0773403Z  Assert.True() Failure
2018-12-21T02:28:46.0773644Z Expected: True
2018-12-21T02:28:46.0773863Z Actual:   False
2018-12-21T02:28:46.0774092Z Stack Trace:
2018-12-21T02:28:46.0774334Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-12-21T02:28:46.0774801Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2018-12-21T02:28:46.0775149Z --- End of stack trace from previous location where exception was thrown ---
2018-12-21T02:28:46.0775356Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-12-21T02:28:46.0775606Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-21T02:28:46.0775874Z    at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.WaitWithoutInlining_DoesNotWaitForOtherInlinedContinuations() in D:\a\1\s\src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs:line 201
```
