### ISSUE TITLE
VSTHRD010 throws ArgumentNullException

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-threading#242]
_From @maxperga on April 19, 2018 3:31_

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer' threw an exception of type 'System.Exception' with message 'Analyzer failure while processing syntax at C:\git\WinAnyCode\Package\CommandHandler.cs(829,26): System.ArgumentNullException Value cannot be null.
Parameter name: values. Syntax: ServiceProvider.GlobalProvider.GetService(typeof(IVsMonitorSelection))'.	WinAnyCode.Package		1	Active	Analyzer 'Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: WinAnyCode.Package
SyntaxTree: C:\git\WinAnyCode\Package\CommandHandler.cs
SyntaxNode: ServiceProvider.GlobalProvider. ... [InvocationExpressionSyntax]@[35032..35102) (828,25)-(828,95)

```
System.Exception: Analyzer failure while processing syntax at C:\git\WinAnyCode\Package\CommandHandler.cs(829,26): System.ArgumentNullException Value cannot be null.
Parameter name: values. Syntax: ServiceProvider.GlobalProvider.GetService(typeof(IVsMonitorSelection)) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: values
   at System.String.Join(String separator, IEnumerable`1 values)
   at Microsoft.VisualStudio.Threading.Analyzers.CommonInterest.QualifiedType.ToString()
   at Microsoft.VisualStudio.Threading.Analyzers.CommonInterest.QualifiedMember.ToString()
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer.MethodAnalyzer.AnalyzeTypeWithinContext(ITypeSymbol type, ISymbol symbol, SyntaxNodeAnalysisContext context, Location focusDiagnosticOn)
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer.MethodAnalyzer.AnalyzeInvocation(SyntaxNodeAnalysisContext context)
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<>c__DisplayClass0_0.<DebuggableWrapper>b__0(SyntaxNodeAnalysisContext ctxt)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<>c__DisplayClass0_0.<DebuggableWrapper>b__0(SyntaxNodeAnalysisContext ctxt)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
System.ArgumentNullException: Value cannot be null.
Parameter name: values
   at System.String.Join(String separator, IEnumerable`1 values)
   at Microsoft.VisualStudio.Threading.Analyzers.CommonInterest.QualifiedType.ToString()
   at Microsoft.VisualStudio.Threading.Analyzers.CommonInterest.QualifiedMember.ToString()
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer.MethodAnalyzer.AnalyzeTypeWithinContext(ITypeSymbol type, ISymbol symbol, SyntaxNodeAnalysisContext context, Location focusDiagnosticOn)
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer.MethodAnalyzer.AnalyzeInvocation(SyntaxNodeAnalysisContext context)
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<>c__DisplayClass0_0.<DebuggableWrapper>b__0(SyntaxNodeAnalysisContext ctxt)
```

This is the block I have starting at line 828:

```cs
        public bool OptionRazzleWindowEnabled
        {
            get
            {
                return _settings.OptionRazzleWindowEnabled;
            }

            set
            {
                _settings.OptionRazzleWindowEnabled = value;
            }
        }
```

About the "_settings", it's defined like: 

```cs
        [Import]
        private IUserSettings _settings;
```

Meanwhile its property is defined in this way:

```cs
        /// <summary>
        /// Property representing the state (enabled/disabled) of the 'Razzle Window' feature.
        /// </summary>
        bool OptionRazzleWindowEnabled
        {
            get;
            set;
        }
```

_Copied from original issue: Microsoft/VSSDK-Analyzers#48_

**Comment by AArnott** [comment]
Thanks for reporting. What version of the analyzers do you have installed?

**Comment by maxperga** [comment]
Sorry for forgetting about it.
I'm using v15.6.56-beta .

**Comment by AArnott** [comment]
Thanks for reporting it. I haven't been able to reproduce this. I see you included source code, but it doesn't seem to match the exception message, which states the SyntaxNode being evaluated at the time was `ServiceProvider.GlobalProvider.GetService(typeof(IVsMonitorSelection));` Can you perhaps find this and more of its context to share so I can repro?

**Comment by AArnott** [comment]
Hmmm... There is no 15.6.56-beta on nuget.org or anywhere else that I can see. Can you double-check that number? There is a 15.6.*4*6 (not beta). Is that the one you're using?

**Comment by maxperga** [comment]
I provided you the version of the Microsoft.VisualStudio.SDK.Analyzers.
The version of the Microsoft.VisualStudio.Threading.Analyzers used is 15.6.46

**Comment by maxperga** [comment]
About the function you mentioned above is:
        internal static bool IsUIContextActive(Guid context)
        {
            ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();

==>            var monSel = ServiceProvider.GlobalProvider.GetService(typeof(IVsMonitorSelection)) as IVsMonitorSelection;
            uint contextCookie;
            bool result = false;

**Comment by AArnott** [comment]
Thanks. I'll look more into it today. 

In the meantime, you're missing an `await` on your first line. `SwitchToMainThreadAsync` is ineffective if you don't actually *await* it. Since you're in a sync method, you'd need to make it async, or use `JoinableTaskFactory.Run` around the whole method body.

**Comment by AArnott** [comment]
Or call `ThreadHelper.ThrowIfNotOnUIThread()` which is preferred over using JTF.Run since it won't block a background thread.

**Comment by AArnott** [comment]
I'm unable to reproduce the problem with v15.6.46 using this file:
```cs
using System;
using Microsoft.VisualStudio.Shell;
using Microsoft.VisualStudio.Shell.Interop;

class Package
{
    internal static bool IsUIContextActive(Guid context)
    {
        ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();

        var monSel = ServiceProvider.GlobalProvider.GetService(typeof(IVsMonitorSelection)) as IVsMonitorSelection;
        uint contextCookie;
        bool result = false;
        return result;
    }
}
```

If you can send a full file that reproduces the problem (perhaps your original, or whittled down to the minimum required), I will be happy to continue to investigate. Otherwise I'm going to have to close this as not repro.
