### ISSUE TITLE
VSTHRD010 throws InvalidCastException when span is ambiguous

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#270]
```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax'.
   at async Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageCodeFix.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.AddDocumentFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetDiagnosticsAndCodeActions(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by AArnott** [comment]
What version was this on? Repro steps?

**Comment by sharwell** [comment]
Version 15.8.64-beta

Repro steps are unclear. I have a locally-modified checkout of GitExtensions. Prior to adding some calls to `ThrowIfNotOnUIThread` I wasn't even able to get a build (csc.exe exited with code 1). At some point a Fix All produced the above failure with a stack trace, which I'm hoping was _somehow_ the cause of the other failures.

**Comment by AArnott** [comment]
I don't think a code fix provider could possibly cause a compile break, since fixers aren't run during compilation. Even the analyzer isn't supposed to break a compilation -- it's just emitted as a failure and it goes on. But of course if we can fix this, we should.

**Comment by AArnott** [comment]
From the location the exception must have been thrown from I can only speculate that the way the BatchFixer does its work is to invoke one fix after another, even though the locations of diagnostics can be outdated, resulting in a fixer being run on a bad location. The diagnostics are always placed on expressions, but somehow the pointer ended up being on an argument. 

I'm not sure how to defend against such unexpected shifts in location for a diagnostic in its fixer. Should it quietly no-op when something unexpected occurs like this?

**Comment by sharwell** [comment]
Found a way to reproduce this:

1. Add `[System.Windows.Forms.*]` to the set of members requiring main thread
2. Pass `(Control)sender` as the argument in a call

The span of the expression and argument are the same, so when the code fix operation attempts to locate the expression it finds the wrong syntax node.

**Comment by sharwell** [comment]
> ... I can only speculate that the way the BatchFixer does its work ...

The batch fixer applies all fixes to the original code, and then merges the results.

**Comment by AArnott** [comment]
> The span of the expression and argument are the same

I wondered if that would be a problem at first, but then I figured that the argument syntax would have to be larger because it would include the trailing comma. I'll have to find the node I want be walking down the tree, I guess.
