### ISSUE TITLE
Unstable test: KeysCollectable

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-threading#282]
In [this appveyor build](https://ci.appveyor.com/project/AArnott/vs-threading/build/15.8.81-beta+R#L983), the test failed with this output:

```
[xUnit.net 00:00:10.2106789]     Microsoft.VisualStudio.Threading.Tests.WeakKeyDictionaryTests.KeysCollectable [FAIL]
[xUnit.net 00:00:10.2108854]       Actual difference is -15865064.
[xUnit.net 00:00:10.2109402]       Expected: True
[xUnit.net 00:00:10.2109814]       Actual:   False
[xUnit.net 00:00:10.2119533]       Stack Trace:
[xUnit.net 00:00:10.2160650]         C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\WeakKeyDictionaryTests.cs(142,0): at Microsoft.VisualStudio.Threading.Tests.WeakKeyDictionaryTests.KeysCollectable()
[xUnit.net 00:00:10.2170002]       Output:
[xUnit.net 00:00:10.2170754]         Start 202275912, end 218140976, diff -15865064
Failed   Microsoft.VisualStudio.Threading.Tests.WeakKeyDictionaryTests.KeysCollectable
Error Message:
 Actual difference is -15865064.
Expected: True
Actual:   False
Stack Trace:
   at Microsoft.VisualStudio.Threading.Tests.WeakKeyDictionaryTests.KeysCollectable() in C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading.Tests\WeakKeyDictionaryTests.cs:line 142
Standard Output Messages:
 Start 202275912, end 218140976, diff -15865064
```

**Comment by AArnott** [comment]
And [again](https://andrewarnott.visualstudio.com/OSS/_build/results?buildId=384&view=logs):

```
2018-10-10T00:07:26.3316917Z [xUnit.net 00:00:42.4547528]     Microsoft.VisualStudio.Threading.Tests.WeakKeyDictionaryTests.KeysCollectable [FAIL]
2018-10-10T00:07:26.3317929Z [xUnit.net 00:00:42.4559163]       Actual difference is -585376.
2018-10-10T00:07:26.3318506Z [xUnit.net 00:00:42.4560241]       Expected: True
2018-10-10T00:07:26.3318660Z [xUnit.net 00:00:42.4560723]       Actual:   False
2018-10-10T00:07:26.3318791Z [xUnit.net 00:00:42.4570607]       Stack Trace:
2018-10-10T00:07:26.3318944Z [xUnit.net 00:00:42.4586950]         D:\a\1\s\src\Microsoft.VisualStudio.Threading.Tests\WeakKeyDictionaryTests.cs(142,0): at Microsoft.VisualStudio.Threading.Tests.WeakKeyDictionaryTests.KeysCollectable()
2018-10-10T00:07:26.3319072Z [xUnit.net 00:00:42.4597089]       Output:
2018-10-10T00:07:26.3319212Z [xUnit.net 00:00:42.4597804]         Start 266210064, end 266795440, diff -585376
2018-10-10T00:07:26.7373342Z Failed   Microsoft.VisualStudio.Threading.Tests.WeakKeyDictionaryTests.KeysCollectable
2018-10-10T00:07:26.7451714Z Error Message:
2018-10-10T00:07:26.7451819Z  Actual difference is -585376.
2018-10-10T00:07:26.7451931Z Expected: True
2018-10-10T00:07:26.7452206Z Actual:   False
2018-10-10T00:07:26.7452272Z Stack Trace:
2018-10-10T00:07:26.7452539Z    at Microsoft.VisualStudio.Threading.Tests.WeakKeyDictionaryTests.KeysCollectable() in D:\a\1\s\src\Microsoft.VisualStudio.Threading.Tests\WeakKeyDictionaryTests.cs:line 142
2018-10-10T00:07:26.7452604Z Standard Output Messages:
2018-10-10T00:07:26.7452660Z  Start 266210064, end 266795440, diff -585376
```
