### ISSUE TITLE
Unstable test: HangReportNotSuppressedOnLongRunningTaskJoinCancelled

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-threading#360]
The `HangReportNotSuppressedOnLongRunningTaskJoinCancelled` test [failed on appveyor](https://ci.appveyor.com/project/AArnott/vs-threading/build/16.0.42-beta+gb26dd38371#L931):

```
    HangReportNotSuppressedOnLongRunningTaskJoinCancelled [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        src\Microsoft.VisualStudio.Threading.Tests\JoinableTaskContextTests.cs(324,0): at Microsoft.VisualStudio.Threading.Tests.JoinableTaskContextTests.HangReportNotSuppressedOnLongRunningTaskJoinCancelled()
    HangReportNotSuppressedOnLongRunningTaskCompleted [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        src\Microsoft.VisualStudio.Threading.Tests\JoinableTaskContextTests.cs(357,0): at Microsoft.VisualStudio.Threading.Tests.JoinableTaskContextTests.HangReportNotSuppressedOnLongRunningTaskCompleted()
```

**Comment by AArnott** [comment]
and [again](https://andrewarnott.visualstudio.com/OSS/_build/results?buildId=532&view=logs)

```
2018-11-10T07:40:29.5985071Z Failed   HangReportNotSuppressedOnLongRunningTaskJoinCancelled
2018-11-10T07:40:29.5985662Z Error Message:
2018-11-10T07:40:29.5985866Z  Assert.True() Failure
2018-11-10T07:40:29.5986001Z Expected: True
2018-11-10T07:40:29.5986132Z Actual:   False
2018-11-10T07:40:29.5986296Z Stack Trace:
2018-11-10T07:40:29.5986649Z    at Microsoft.VisualStudio.Threading.Tests.JoinableTaskContextTests.HangReportNotSuppressedOnLongRunningTaskJoinCancelled() in D:\a\1\s\src\Microsoft.VisualStudio.Threading.Tests\JoinableTaskContextTests.cs:line 324
```

**Comment by AArnott** [comment]
and [again](https://dev.azure.com/azure-public/vside/_build/results?buildId=676):

```
2018-12-01T19:03:51.1915399Z [xUnit.net 00:07:36.4405858]     HangReportNotSuppressedOnLongRunningTaskJoinCancelled [FAIL]
2018-12-01T19:03:51.2039601Z [xUnit.net 00:07:36.4424245]       Assert.True() Failure
2018-12-01T19:03:51.2040677Z [xUnit.net 00:07:36.4425061]       Expected: True
2018-12-01T19:03:51.2041118Z [xUnit.net 00:07:36.4425468]       Actual:   False
2018-12-01T19:03:51.2041501Z [xUnit.net 00:07:36.4432549]       Stack Trace:
2018-12-01T19:03:51.2042171Z [xUnit.net 00:07:36.4468306]         src\Microsoft.VisualStudio.Threading.Tests\JoinableTaskContextTests.cs(324,0): at Microsoft.VisualStudio.Threading.Tests.JoinableTaskContextTests.HangReportNotSuppressedOnLongRunningTaskJoinCancelled()
```
