### ISSUE TITLE
Code fix for VSTHRD010 builds invalid syntax tree

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-threading#373]
#### Bug description

Per the discussion in https://github.com/Microsoft/vs-threading/pull/359#discussion_r216208485 with @sharwell, find the analyzer tests that ignore this error in our code fix using this language:

```cs
                // Expected: SimpleMemberAccessExpression
                // Actual:   QualifiedName
                CodeFixValidationMode = CodeFixValidationMode.None,
```

We should fix the bug and remove the test suppression.

**Comment by AArnott** [comment]
@sharwell The *actual* assertion failure reported from this issue is *quite* opaque. It would be marvelous if this could give the enum value names instead of their ordinal values.

```
Test Name:	InvokeVsSolutionNoCheck_InCtor
Test FullName:	Microsoft.VisualStudio.Threading.Analyzers.Tests.VSTHRD010MainThreadUsageAnalyzerTests.InvokeVsSolutionNoCheck_InCtor
Test Source:	D:\git\threading\src\Microsoft.VisualStudio.Threading.Analyzers.Tests\VSTHRD010MainThreadUsageAnalyzerTests.cs : line 188
Test Outcome:	Failed
Test Duration:	0:00:00.156

Result StackTrace:	
at Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier.Equal[T](T expected, T actual, String message) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Testing.Verifiers.XUnit/XUnitVerifier.cs:line 20
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.Visit(SyntaxNode node) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 740
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertNodesEqual(SyntaxNode expected, SyntaxNode actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 746
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertChildSyntaxListEqual(ChildSyntaxList expected, ChildSyntaxList actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 762
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.Visit(SyntaxNode node) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 741
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertNodesEqual(SyntaxNode expected, SyntaxNode actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 746
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertChildSyntaxListEqual(ChildSyntaxList expected, ChildSyntaxList actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 762
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.Visit(SyntaxNode node) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 741
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertNodesEqual(SyntaxNode expected, SyntaxNode actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 746
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertChildSyntaxListEqual(ChildSyntaxList expected, ChildSyntaxList actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 762
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.Visit(SyntaxNode node) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 741
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertNodesEqual(SyntaxNode expected, SyntaxNode actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 746
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertChildSyntaxListEqual(ChildSyntaxList expected, ChildSyntaxList actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 762
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.Visit(SyntaxNode node) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 741
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertNodesEqual(SyntaxNode expected, SyntaxNode actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 746
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertChildSyntaxListEqual(ChildSyntaxList expected, ChildSyntaxList actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 762
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.Visit(SyntaxNode node) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 741
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertNodesEqual(SyntaxNode expected, SyntaxNode actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 746
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertChildSyntaxListEqual(ChildSyntaxList expected, ChildSyntaxList actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 762
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.Visit(SyntaxNode node) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 741
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertNodesEqual(SyntaxNode expected, SyntaxNode actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 746
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertChildSyntaxListEqual(ChildSyntaxList expected, ChildSyntaxList actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 762
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.Visit(SyntaxNode node) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 741
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.TreeEqualityVisitor.AssertNodesEqual(SyntaxNode expected, SyntaxNode actual, Boolean checkTrivia) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 746
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.<RecreateProjectDocumentsAsync>d__44.MoveNext() in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 493
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.<FixEachAnalyzerDiagnosticAsync>d__42.MoveNext() in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 417
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.<VerifyFixAsync>d__40.MoveNext() in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 325
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.<VerifyFixAsync>d__39.MoveNext() in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 304
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.<RunAsync>d__36.MoveNext() in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Threading.Analyzers.Tests.VSTHRD010MainThreadUsageAnalyzerTests.<InvokeVsSolutionNoCheck_InCtor>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Assert.Equal() Failure
Expected: 8689
Actual:   8617
```
