### ISSUE TITLE
Unstable test: AsyncPumpReleasedAfterExecution

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-threading#433]
From [this build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2282819):

```
2018-12-17T17:48:40.1931861Z Failed   AsyncPumpReleasedAfterExecution(throwInValueFactory: False)
2018-12-17T17:48:40.1944221Z Error Message:
2018-12-17T17:48:40.1944590Z  Assert.False() Failure
2018-12-17T17:48:40.1944766Z Expected: False
2018-12-17T17:48:40.1944822Z Actual:   True
2018-12-17T17:48:40.1944897Z Stack Trace:
2018-12-17T17:48:40.1944985Z    at Microsoft.VisualStudio.Threading.Tests.AsyncLazyTests.<AsyncPumpReleasedAfterExecution>d__8.MoveNext() in E:\A\_work\326\s\src\Microsoft.VisualStudio.Threading.Tests\AsyncLazyTests.cs:line 219
2018-12-17T17:48:40.1945117Z --- End of stack trace from previous location where exception was thrown ---
2018-12-17T17:48:40.1945187Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-12-17T17:48:40.1945273Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-17T17:48:40.1945347Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-17T17:48:40.1945420Z    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2018-12-17T17:48:40.1945502Z    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
2018-12-17T17:48:40.1945571Z --- End of stack trace from previous location where exception was thrown ---
2018-12-17T17:48:40.1945658Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-12-17T17:48:40.1945726Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-17T17:48:40.1945831Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-17T17:48:40.1945905Z    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2018-12-17T17:48:40.1945972Z    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
2018-12-17T17:48:40.1946056Z --- End of stack trace from previous location where exception was thrown ---
2018-12-17T17:48:40.1946126Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-12-17T17:48:40.1946209Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-17T17:48:40.1946283Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-17T17:48:40.1946370Z    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2018-12-17T17:48:40.1946437Z    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

**Comment by AArnott** [comment]
And [again](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2293231&view=ms.vss-test-web.test-result-details) in 5e295a9:

```
2018-12-21T16:04:57.0255533Z Failed   AsyncPumpReleasedAfterExecution(throwInValueFactory: False)
2018-12-21T16:04:57.0256278Z Error Message:
2018-12-21T16:04:57.0256395Z  Assert.False() Failure
2018-12-21T16:04:57.0256470Z Expected: False
2018-12-21T16:04:57.0256523Z Actual:   True
2018-12-21T16:04:57.0256590Z Stack Trace:
2018-12-21T16:04:57.0256701Z    at Microsoft.VisualStudio.Threading.Tests.AsyncLazyTests.<AsyncPumpReleasedAfterExecution>d__8.MoveNext() in E:\A\_work\1016\s\src\Microsoft.VisualStudio.Threading.Tests\AsyncLazyTests.cs:line 219
2018-12-21T16:04:57.0256806Z --- End of stack trace from previous location where exception was thrown ---
2018-12-21T16:04:57.0256893Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-12-21T16:04:57.0256967Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-21T16:04:57.0257063Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-21T16:04:57.0257137Z    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2018-12-21T16:04:57.0257221Z    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
2018-12-21T16:04:57.0257303Z --- End of stack trace from previous location where exception was thrown ---
2018-12-21T16:04:57.0257390Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-12-21T16:04:57.0257679Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-21T16:04:57.0257768Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-21T16:04:57.0257841Z    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2018-12-21T16:04:57.0257908Z    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
2018-12-21T16:04:57.0257992Z --- End of stack trace from previous location where exception was thrown ---
2018-12-21T16:04:57.0258061Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-12-21T16:04:57.0258145Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-21T16:04:57.0258220Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-21T16:04:57.0258307Z    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2018-12-21T16:04:57.0258477Z    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```
