### ISSUE TITLE
Unstable test: TransitionToMainThreadRaisedWhenSwitchingToMainThread 

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-threading#44]
This test has been [observed to fail](https://ci.appveyor.com/project/AArnott/vs-threading/build/15.0.200+gcb3aa2e481.R#L39)

```
   TransitionToMainThreadRaisedWhenSwitchingToMainThread [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   0
      Stack Trace:
        src\Microsoft.VisualStudio.Threading.Tests.Shared\JoinableTaskTests.cs(529,0): at Microsoft.VisualStudio.Threading.Tests.JoinableTaskTests.<>c__DisplayClass19_0.<<TransitionToMainThreadRaisedWhenSwitchingToMainThread>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        src\Microsoft.VisualStudio.Threading.Shared\JoinableTask.cs(519,0): at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        src\Microsoft.VisualStudio.Threading.Shared\JoinableTask.cs(884,0): at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
        src\Microsoft.VisualStudio.Threading.Shared\JoinableTask.cs(497,0): at Microsoft.VisualStudio.Threading.JoinableTask.Join(CancellationToken cancellationToken)
        src\Microsoft.VisualStudio.Threading.Tests.Shared\JoinableTaskTests.cs(546,0): at Microsoft.VisualStudio.Threading.Tests.JoinableTaskTests.TransitionToMainThreadRaisedWhenSwitchingToMainThread()
```

**Comment by sharwell** [comment]
I fixed this by adding a small delay after [these assertions](https://github.com/Microsoft/vs-threading/blob/1c9566954617fc53d137357e3154f365cae0e1fe/src/Microsoft.VisualStudio.Threading.Tests.Shared/JoinableTaskTests.cs#L527-L528) to ensure the background operation doesn't complete before the code awaits the result.
