### ISSUE TITLE
SynchronizationContextSend_ProducesDiagnostic

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-threading#445]
From [this build](https://dev.azure.com/azure-public/vside/_build/results?buildId=1284) (commit dda65cd):

```
2018-12-21T02:21:50.2029836Z Failed   SynchronizationContextSend_ProducesDiagnostic
2018-12-21T02:21:50.2036769Z Error Message:
2018-12-21T02:21:50.2332884Z  Mismatch between number of diagnostics returned, expected "1" actual "0"
2018-12-21T02:21:50.2385745Z 
2018-12-21T02:21:50.2386103Z Diagnostics:
2018-12-21T02:21:50.2387477Z     NONE.
2018-12-21T02:21:50.2387664Z 
2018-12-21T02:21:50.2387815Z Expected: True
2018-12-21T02:21:50.2387940Z Actual:   False
2018-12-21T02:21:50.2388064Z Stack Trace:
2018-12-21T02:21:50.2388701Z    at Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier.Equal[T](T expected, T actual, String message) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Testing.Verifiers.XUnit/XUnitVerifier.cs:line 26
2018-12-21T02:21:50.2388968Z    at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticResults(IEnumerable`1 actualResults, ImmutableArray`1 analyzers, DiagnosticResult[] expectedResults) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 191
2018-12-21T02:21:50.2389195Z    at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.<VerifyDiagnosticsAsync>d__46.MoveNext() in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 150
2018-12-21T02:21:50.2389406Z --- End of stack trace from previous location where exception was thrown ---
2018-12-21T02:21:50.2390137Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-21T02:21:50.2390345Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-21T02:21:50.2390521Z    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
2018-12-21T02:21:50.2390732Z    at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.<RunAsync>d__36.MoveNext() in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 182
2018-12-21T02:21:50.2390927Z --- End of stack trace from previous location where exception was thrown ---
2018-12-21T02:21:50.2391093Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-21T02:21:50.2391311Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-21T02:21:50.2391569Z    at Microsoft.VisualStudio.Threading.Analyzers.Tests.VSTHRD001UseSwitchToMainThreadAsyncAnalyzerTests.<SynchronizationContextSend_ProducesDiagnostic>d__6.MoveNext() in D:\a\1\s\src\Microsoft.VisualStudio.Threading.Analyzers.Tests\VSTHRD001UseSwitchToMainThreadAsyncAnalyzerTests.cs:line 119
2018-12-21T02:21:50.2392066Z --- End of stack trace from previous location where exception was thrown ---
2018-12-21T02:21:50.2392212Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-21T02:21:50.2392376Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-21T02:21:50.2392521Z --- End of stack trace from previous location where exception was thrown ---
2018-12-21T02:21:50.2392676Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-21T02:21:50.2392819Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-21T02:21:50.2392976Z --- End of stack trace from previous location where exception was thrown ---
2018-12-21T02:21:50.2393125Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-21T02:21:50.2393296Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by AArnott** [comment]
Fixed by 5e295a9bb4dc6a468634ee2ead37b4453579b9d9
