### ISSUE TITLE
VSTHRD003 exception for field in another assembly

### ISSUE THREAD

**Issue by sharwell** [microsoft/vs-threading#472]
#### Bug description

VSTHRD003 produces an AD0001 error in the IDE when code references a field in another project.

#### Repro steps

First assembly:

```
public static class SpecialTasks {
  public static readonly Task<bool> True = Task.FromResult(true);
}
```

Second assembly:

```
public static class Boom {
  Task<bool> MyMethodAsync() {
    return SpecialTasks.True;
  }
}
```

1. Define the above assemblies
2. Add a ProjectReference from the second assembly to the first
3. Open **Boom.cs** in Visual Studio

#### Expected behavior

No exception.

#### Actual behavior

```
Severity    Code    Description    Project    File    Line    Suppression State    Detail Description
Error    AD0001    Analyzer 'Microsoft.VisualStudio.Threading.Analyzers.VSTHRD003UseJtfRunAsyncAnalyzer' threw an exception of type 'System.Exception' with message 'Analyzer failure while processing syntax at C:\dev\roslyn\src\Features\Core\Portable\Diagnostics\DiagnosticAnalyzerService.cs(147,13): System.ArgumentException SyntaxTree is not part of the compilation

Parameter name: syntaxTree. Syntax: return SpecializedTasks.False;'.    Microsoft.CodeAnalysis.Features        1    Active    Analyzer 'Microsoft.VisualStudio.Threading.Analyzers.VSTHRD003UseJtfRunAsyncAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.Features
SyntaxTree: C:\dev\roslyn\src\Features\Core\Portable\Diagnostics\DiagnosticAnalyzerService.cs
SyntaxNode: return SpecializedTasks.False; [ReturnStatementSyntax]@[7250..7280) (146,12)-(146,42)

System.Exception: Analyzer failure while processing syntax at C:\dev\roslyn\src\Features\Core\Portable\Diagnostics\DiagnosticAnalyzerService.cs(147,13): System.ArgumentException SyntaxTree is not part of the compilation
Parameter name: syntaxTree. Syntax: return SpecializedTasks.False; ---> System.ArgumentException: SyntaxTree is not part of the compilation
Parameter name: syntaxTree
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.CodeAnalysis.Compilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD003UseJtfRunAsyncAnalyzer.AnalyzeAwaitedOrReturnedExpression(ExpressionSyntax expressionSyntax, SyntaxNodeAnalysisContext context, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD003UseJtfRunAsyncAnalyzer.AnalyzeReturnStatement(SyntaxNodeAnalysisContext context)
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<>c__DisplayClass0_0.<DebuggableWrapper>b__0(SyntaxNodeAnalysisContext ctxt)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<>c__DisplayClass0_0.<DebuggableWrapper>b__0(SyntaxNodeAnalysisContext ctxt)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__50`1.<ExecuteSyntaxNodeAction>b__50_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
System.ArgumentException: SyntaxTree is not part of the compilation
Parameter name: syntaxTree
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.CodeAnalysis.Compilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD003UseJtfRunAsyncAnalyzer.AnalyzeAwaitedOrReturnedExpression(ExpressionSyntax expressionSyntax, SyntaxNodeAnalysisContext context, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD003UseJtfRunAsyncAnalyzer.AnalyzeReturnStatement(SyntaxNodeAnalysisContext context)
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<>c__DisplayClass0_0.<DebuggableWrapper>b__0(SyntaxNodeAnalysisContext ctxt)
```

- Version used: 16.0.102
- Application (if applicable): Visual Studio 2019 Preview 4.1 SVC 1

**Comment by AArnott** [comment]
@sharwell does the analyzer test framework we're using allow us to simulate multi-project scenarios to repro this?

**Comment by sharwell** [comment]
@AArnott yes, but it's a bit clumsy. I implemented a test for a case like this in dotnet/machinelearning:
https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.CodeAnalyzer.Tests/Code/BestFriendTest.cs
