### ISSUE TITLE
Unstable test: ToTaskOnHandleSignaledAfterNonZeroTimeout 

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#529]
In [this build](https://dev.azure.com/azure-public/vside/_build/results?buildId=7484&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=1fe6a80f-c499-5c44-93a4-d7854bf81728&l=337) 

```
X ToTaskOnHandleSignaledAfterNonZeroTimeout [1s 933ms]
  Error Message:
   System.TimeoutException : The operation has timed out.
  Stack Trace:
     at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__5.MoveNext() in d:\a\1\s\src\Microsoft.VisualStudio.Threading\TplExtensions.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__6`1.MoveNext() in d:\a\1\s\src\Microsoft.VisualStudio.Threading\TplExtensions.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.Tests.TplExtensionsTests.<ToTaskOnHandleSignaledAfterNonZeroTimeout>d__44.MoveNext() in d:\a\1\s\src\Microsoft.VisualStudio.Threading.Tests\TplExtensionsTests.cs:line 752
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by AArnott** [comment]
and [this build](https://dev.azure.com/azure-public/vside/_build/results?buildId=7496&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=1fe6a80f-c499-5c44-93a4-d7854bf81728&l=321)
