### ISSUE TITLE
Unstable test: NoLeakForContestedRequests_ThatAreCanceled

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#530]
The test failed in [this build](https://dev.azure.com/azure-public/vside/_build/results?buildId=7485&view=ms.vss-test-web.build-test-results-tab&runId=1010830&resultId=100279&paneView=debug):

```
Leaks observed in every iteration.
Expected: True
Actual: False

   at Microsoft.VisualStudio.Threading.Tests.TestBase.<CheckGCPressureAsync>d__19.MoveNext() in d:\a\1\s\src\Microsoft.VisualStudio.Threading.Tests\TestBase.cs:line 238
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.Tests.AsyncSemaphoreTests.<NoLeakForContestedRequests_ThatAreCanceled>d__23.MoveNext() in d:\a\1\s\src\Microsoft.VisualStudio.Threading.Tests\AsyncSemaphoreTests.cs:line 410
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by AArnott** [comment]
and [failed again](https://dev.azure.com/azure-public/vside/_build/results?buildId=7488&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=1fe6a80f-c499-5c44-93a4-d7854bf81728&l=376)
