### ISSUE TITLE
Unhandled exception in AsyncSemaphore: The LinkedList node does not belong to current LinkedList

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/vs-threading#906]
#### Bug description

While debugging VS, I closed the window then saw this.

```
   at System.Collections.Generic.LinkedList`1.ValidateNode(LinkedListNode`1 node) in f:\dd\NDP\fx\src\compmod\system\collections\generic\linkedlist.cs:line 380
   at Microsoft.VisualStudio.Threading.AsyncSemaphore.CancellationHandler(Object state) in C:\a\1\s\src\Microsoft.VisualStudio.Threading\AsyncSemaphore.cs:line 223
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

![image](https://user-images.githubusercontent.com/350947/132335087-aa214883-7344-4d2a-a5b9-6943d1e2fd66.png)

#### Repro steps
Is not reliably reproduceable. 

- Version used: devenv 17.0.0 Preview 4.0 [31702.50.main]

#### Additional context
I captured a dump of the debuggee, in case that'd be useful. It's in `\\mlangfs1\public\drnoakes\20210907-devenv-hang-async-semaphore-linked-list`

**Comment by AArnott** [comment]
Investigation notes:
* The `LinkedList<T>` believes itself to be empty.
* The node believes it belongs to no list.
* The `AsyncSemaphore` has been disposed.
* Upon disposal, the `AsyncSemaphore` calls `nodePool.Clear()` which would cause the list to be empty and the nodes to believe themselves unowned, even though they still belong to a `WaiterInfo` object.
